//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndgameCheckmatePractice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EndgameCheckmatePractice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black_king {
            get {
                object obj = ResourceManager.GetObject("black_king", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- How to Play --
        ///
        ///
        ///Endgame Checkmate Practice allows you to practice playing the end of a game of Chess. This document does not describe the full rules of chess, only those needed for the endgame.
        ///
        ///You control the white pieces, and the computer controls a single black piece. The computer&apos;s piece is called the Black King. You start with at least two pieces, one of which is called the White King. You must choose one or more pieces with other names, such as Knights, Queens, or Rooks.
        ///
        ///You and the compu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string How_To_Play {
            get {
                return ResourceManager.GetString("How_To_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Recommended Piece Sets --
        ///
        ///
        ///♔+♕ vs ♚
        ///King and Queen vs King
        ///Easy, very common
        ///
        ///♔+♖+♖ vs ♚
        ///King and 2 Rooks vs King
        ///Easy
        ///
        ///♔+♖ vs ♚
        ///King and Rook vs King
        ///Medium, somewhat common
        ///
        ///♔+♗+♘ vs ♚
        ///King, Bishop, and Knight vs King
        ///Hard
        ///
        ///♔+♘+♘+♘ vs ♚
        ///King and 3 Knights vs King
        ///Medium
        ///
        ///♔+♘+♘ vs ♚
        ///King and 2 Knights vs King
        ///Medium (if the computer played perfectly, it would be impossible, but the computer will not)
        ///
        ///♔+♘ vs ♚
        ///King and Knight vs King
        ///Impossible (have fun playing around with [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Recommended_Piece_Sets {
            get {
                return ResourceManager.GetString("Recommended_Piece_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_bishop {
            get {
                object obj = ResourceManager.GetObject("white_bishop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_fairy_champion {
            get {
                object obj = ResourceManager.GetObject("white_fairy_champion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_fairy_ferz {
            get {
                object obj = ResourceManager.GetObject("white_fairy_ferz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_fairy_mann {
            get {
                object obj = ResourceManager.GetObject("white_fairy_mann", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_fairy_wazir {
            get {
                object obj = ResourceManager.GetObject("white_fairy_wazir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_fairy_wizard {
            get {
                object obj = ResourceManager.GetObject("white_fairy_wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_king {
            get {
                object obj = ResourceManager.GetObject("white_king", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_knight {
            get {
                object obj = ResourceManager.GetObject("white_knight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_queen {
            get {
                object obj = ResourceManager.GetObject("white_queen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_rook {
            get {
                object obj = ResourceManager.GetObject("white_rook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
